### ISSUE TITLE
Define min and max input variables

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#94]
@teixeirak 
We need to define how systematically we will come up with recommendations for a min or max input (ex. dbh) in the sitespecies table. I am currently transferring the original ranges as a guide to define our suggestions. 

This is the definition for these variables:

----
min_input_variable | Recommended minimum value of independent   (input) variable (e.g., dbh) over which the equation should be applied (may   or may not match the range over which the equation was developed)
-- | --
max_input_variable | Recommended maximum value of  independent (input) variable (e.g., dbh)   over which the equation should be applied (may or may not match the range   over which the equation was developed)

**Comment by teixeirak** [comment]
Thanks! That's a good first step.  Next step will be to identify cases in which the original ranges are not appropriate. There will be two major cases: 

**1. Where there is overlap in the size range between two expert-selected equations.** For example, *Acer rubrum* at Lilly Dicky as two equations, one for 1-55cm and one for .25-5.73 cm. (This is a bit of a weird example because the 1-55cm equation covers the full lower end of trees that we measure, but I'll stick with it as an example.) I'd look at several factors:
- check the quality of the equations. If one has low quality (e.g., low sample size, no indication of bias correction) and isn't truly necessary, it probably makes sense just to drop it. 
- check whether they cross. It's probably best to write a script for this. If they cross, the crossing point should be the transition from using one equation to the other.  If they don't cross and both are needed, I'm not sure what to do.

**2. where the equation doesn't cover the full size range observed in ForestGEO plots** We need complete coverage, but also to be very careful extrapolating beyond the range for which the allometry was developed. An example would be *Amelanchier arborea* at Lilly Dicky. The equations only go down to 5cm DBH, but we need down to 1cm. The logical thing to do here would probably be to fill in a generic allometry (in this case and probably many others, perhaps a shrub equation-- see issue #88). Once again, we need to consider where the equations cross in order to decide where to switch between generic and taxa-specific.

At the upper end, there may be individuals larger than those for which the allometries were developed (e.g., a >55cm *Acer rubrum* at Lilly Dicky). In this case, we may need to switch to the generic equation, but again we hit the issue of equations crossing. 

I think that in both cases, we'd be okay extrapolating the expert-selected equations somewhat beyond the observed range, provided that they don't shoot off into unreasonable values.

I'd like to discuss how to handle all this in person (also with @ValentineHerr and @cpiponiot), and come up with a consistent set of rules for determining which equation to apply. In the meantime, let's figure out how many of each of these cases we have.

**Comment by gonzalezeb** [comment]
Yesterday we created some test that may help to clarify where the equations overlap. See for example this graph for Tilia americana. We have 4 allometries in allodb (2 for AGB and 2 for stems only -Clark equations). We applied the 4 equations to a dbh range of 1-100cm. The dotted line indicates where the equation is out of the dbh range for which it was built.

This, of course, doesn't solve the problem on which equation to recommend but give us a general sense of the allomeries trend. 

![image](https://user-images.githubusercontent.com/26872628/66502637-a7ee1180-ea93-11e9-96b4-d7ff185a5f93.png)

**Comment by teixeirak** [comment]
Thanks! Maybe better to put these on log-log axes? It's impossible to see what's going on at the small size range. 

The easiest would definitely be to just go with chojnacky, as it has the largest DBH span and we wouldn't need to worry about switching allometries, but depending on what happens at the lower end of DBH, it may be worth using a species-specific equation. 

I'll try to discuss tomorrow with @cpiponiot.

**Comment by teixeirak** [comment]
This issue would be solved by #96.
